import type { Metadata } from 'next';
import { Inter, Noto_Sans_JP, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import SideNav from './_components/SideNav';
import Header from './_components/Header';

const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter',
});

const notoSansJP = Noto_Sans_JP({
   subsets: ['latin'],
   variable: '--font-noto-sans-jp',
});

const plusJakartaSans = Plus_Jakarta_Sans({
   subsets: ['latin'],
   variable: '--font-plus-jakarta-sans',
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${inter.variable} ${notoSansJP.variable} ${plusJakartaSans.variable} antialiased`}
      >
         <body>
            <SideNav />
            <main className="flex flex-1 flex-col max-h-screen">
               <Header />
               {children}
            </main>
         </body>
      </html>
   );
}
